baseURL = 'https://nokit.org/'
languageCode = 'en-us'
title = 'NoKit'

[params]
BookSearch = false

[module]

[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[[module.mounts]]
source = 'content'
target = 'content'

[[module.mounts]]
source = 'nokit-drawing-pad/docs'
target = 'content/docs/projects/drawing-pad'

[[module.mounts]]
source = 'nokit-perseverance-rover/docs'
target = 'content/docs/projects/perseverance-rover'

[[module.mounts]]
source = 'nokit-microscope/docs'
target = 'content/docs/projects/microscope'

[[module.mounts]]
source = 'nokit-camera/docs'
target = 'content/docs/projects/camera'

[[module.mounts]]
source = 'nokit-thermal-camera/docs'
target = 'content/docs/projects/thermal-camera'

